### PR TITLE
Bug

### PR DESCRIPTION
**Pull request by mageofboy**
- markings are already Location objects
- Is it alright to inverse_transform lanes here, similar to the detected obstacles, or does the above comment still apply?

### CODE REVIEW

**Comment by ICGog** [comment]
Can you please explain what the bug is? It looks to me that the markings are `Transforms`, and not locations (https://github.com/erdos-project/pylot/blob/master/pylot/perception/detection/lanenet_detection_operator.py#L121).

**Comment by mageofboy** [comment]
> Can you please explain what the bug is? It looks to me that the markings are `Transforms`, and not locations (https://github.com/erdos-project/pylot/blob/master/pylot/perception/detection/lanenet_detection_operator.py#L121).

I guess there is some inconsistency with the perfect lane detection operator. Perfect lane detection calls https://github.com/erdos-project/pylot/blob/ac024de97025e0afad7f08202950e436cf3aed36/pylot/map/hd_map.py#L337
and the function outputs represents lane markings as Locations https://github.com/erdos-project/pylot/blob/ac024de97025e0afad7f08202950e436cf3aed36/pylot/map/hd_map.py#L407

**Comment by mageofboy** [comment]
The fix would be to replace https://github.com/erdos-project/pylot/blob/ac024de97025e0afad7f08202950e436cf3aed36/pylot/map/hd_map.py#L309
with
`        left_markings = [
            pylot.utils.Transform(self._lateral_shift(w.transform, -w.lane_width * 0.5), pylot.utils.Rotation())
            for w in lane_waypoints
        ]
`

**Comment by mageofboy** [comment]
addressed in https://github.com/erdos-project/pylot/pull/244

**Comment by ICGog** [comment]
Closing, as we'll be switching to `Locations` in another PR.

**Pull request closed without merging**
